### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by xJon** [BuiltBrokenModding/MFFS_Classic#34] opened 2018-04-03 22:39 UTC
https://pastebin.com/PWF27tkn
Any idea?

**Comment by Blueletric** [comment] 2018-04-03 23:12
Closing because it is a repeat of another crash brought up by our dev team

**Closed** 2018-04-03 23:13 UTC

**Comment by dmodoomsirius** [comment] 2018-04-04 01:25
Duplicate of https://github.com/BuiltBrokenModding/MFFS_Classic/issues/33

**Comment by xJon** [comment] 2018-04-04 08:50
I'm using the latest public build of MFFS and this is not fixed, will you release the fix soon?
